---
kind: pipeline
type: docker
name: ci

steps:
  - name: install
    image: node:lts
    commands:
      - npm i --silent
    when:
      branch:
        - main
      event:
        - tag

  - name: build/npm-package
    image: node:lts
    environment:
      NODE_ENV: production
    commands:
      - npm run build
    when:
      branch:
        - main
      event:
        - tag

  - name: publish/npm-package
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
      token:
        from_secret: npm_token
    when:
      branch:
        - main
      event:
        - tag
